language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 2Qov064uOLZcZC3gDTFZIhMEZ3I0+v+JkIsKYqQoM7QFwErkmumi9GcYcrufGFIMJCF7AowA6nvQQkiekrLQNbe4bDR4U1EVH0yVv6PMhQL65fxdP2LXseST61lpFg6khvxsJGyBScx+XnQC3I36EkXpjaUZ/EVJEIX6Pr4hWVXZi1kRODGt1UzqLmqEWGLSIxc562wPYuO2SQhfJ2DTcsTK4Lhzu6AsOcQiRb/lSLng4CNEFE6AKhXr92OInzlFbl+j/hZdeDP4hJ55jHrys5KPvNNYgrOR638Jy4aeLuS98Md+poxfKFo1uf4GzG9gVU+RyR5KRXqG/crIpfV5ELAPG8st02sIS1DFh8o2AquGBQnSizqPvlqeme2hApFaDL5cv6pZay6CfSj3LZv/pKDaf0Kqnmye9HPSc9Mr0VEYYMlGTsKh+Vs+a3e5XILWHNH2avqHvgZH2s6taFoq3TYE0Sw9OiZqijkPNSkje10jyD5Yox8Q33Aju6XmGWUupNtH8cCL32VvbJ/7mbGh9AD5+g1MBl1XfTjfDNcARWfwwrtDNuc7HX1DvR1DROmgSBLQbbpLEqKmMeGAWVdS7K5wM7eG4j7+KWRyMjZq6ytrJmbipvU9v5ir6VzPINRc7j78Wg6LPNNdd6FzFyhDV4gnCq/LDSvREby4rUCLC+Q=
  file:
    - "unist-util-size.js"
    - "unist-util-size.min.js"
  on:
    tags: true
    node: '9.0'
